In [1]:
import torch
import numpy

In [2]:
t1=torch.tensor([[1,2]
              ,[3,4]],dtype=torch.float32)
t2=torch.tensor([[9,8]
              ,[7,6]],dtype=torch.float32)

In [3]:
t1[0]

tensor([1., 2.])

In [4]:
t1[0][0]

tensor(1.)

In [5]:
t1+t2

tensor([[10., 10.],
        [10., 10.]])

In [6]:
t1+2

tensor([[3., 4.],
        [5., 6.]])

In [11]:
t1.add(2)

tensor([[3., 4.],
        [5., 6.]])

In [12]:
t1+torch.tensor(numpy.broadcast_to(2,t1.shape),dtype=torch.float32)

tensor([[3., 4.],
        [5., 6.]])

In [14]:
t=([2,3,4] 
   ,[3,0,0]
  ,[1,3,5])
t

([2, 3, 4], [3, 0, 0], [1, 3, 5])