In [23]:
import torch
import numpy

In [24]:
print(torch.__version__)

print(torch.cuda.is_available())
print(torch.cuda.device(0))
print(torch.cuda.device_count())
print(torch.cuda.get_device_name(0))

print(torch.cuda.current_device())
print(torch.version.cuda)
#print("cuda version",torch.cudaprint(.current_device()))


1.6.0+cu101
True
1
GeForce 940M
0
10.1


In [25]:
t=torch.tensor([1,2,3])
t

tensor([1, 2, 3])

In [26]:
t=t.cuda()
t

tensor([1, 2, 3], device='cuda:0')

In [27]:
t1=torch.Tensor()
t1=t1.cuda()
t1

tensor([], device='cuda:0')

In [28]:
print(t1.dtype)
print(t1.device)
print(t1.layout)

torch.float32
cuda:0
torch.strided


In [29]:
t1= torch.tensor([[1,1,1,1],
                  [1,1,1,1]
                 ,[1,1,1,1]
                 ,[1,1,1,1]])
t2= torch.tensor([[2,2,2,2]
                 ,[2,2,2,2]
                 ,[2,2,2,2]
                 ,[2,2,2,2]])
t3=torch.tensor([[3,3,3,3]
                ,[3,3,3,3]
                ,[3,3,3,3]
                ,[3,3,3,3]])

In [30]:
t=torch.stack((t1,t2,t3))
t.shape


torch.Size([3, 4, 4])

In [31]:
t

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

In [32]:
t=t.reshape(3,1,4,4)

In [33]:
t[0]

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [34]:
t[0][0]

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [35]:
t[0][0][0]

tensor([1, 1, 1, 1])

In [36]:
t[0][0][0][0]

tensor(1)

In [37]:
t.reshape(1,-1)[0]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [38]:
t.view(t.numel())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [39]:
t.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [40]:
t.flatten(start_dim=1).shape

torch.Size([3, 16])

In [41]:
t.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [42]:
t.reshape(3,-1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])