In [26]:
import tensorflow as tf

In [27]:
t1=tf.constant([1,1,1])
t2=tf.constant([2,2,2])
t3=tf.constant([3,3,3])

In [28]:
tf.concat((t1,t2,t3), axis=0)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 1, 1, 2, 2, 2, 3, 3, 3], dtype=int32)>

In [29]:
tf.stack((t1,t2,t3),axis=0)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]], dtype=int32)>

In [30]:
tf.concat(
          (tf.expand_dims(t1,0)
          ,tf.expand_dims(t2,0)
          ,tf.expand_dims(t3,0))
          ,axis=0)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]], dtype=int32)>

In [31]:
import torch

In [32]:
t1=torch.tensor([1,1,1])
t2=torch.tensor([2,2,2])
t3=torch.tensor([3,3,3])

In [33]:
torch.cat((t1,t2,t3),dim=0)

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [34]:
torch.stack((t1,t2,t3),dim=0)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [17]:
torch.stack(
          (t1.unsqueeze(0)
          ,t2.unsqueeze(0)
          ,t3.unsqueeze(0))
          ,dim=1)

tensor([[[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]]])

In [24]:
torch.stack(
            (t1,t2,t3)
             ,dim=0)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [25]:
import numpy as np

In [35]:
?? np.stack